/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SurveysRouteImport } from './routes/surveys'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as InternshipsRouteImport } from './routes/internships'
import { Route as GrantsRouteImport } from './routes/grants'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as PublicationsSlugRouteImport } from './routes/publications.$slug'
import { Route as ProgramsSlugRouteImport } from './routes/programs.$slug'
import { Route as MarketsIdRouteImport } from './routes/markets.$id'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminSurveysRouteImport } from './routes/_authenticated/admin/surveys'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminSearchRouteImport } from './routes/_authenticated/admin/search'
import { Route as AuthenticatedAdminPublicationsRouteImport } from './routes/_authenticated/admin/publications'
import { Route as AuthenticatedAdminProgramsRouteImport } from './routes/_authenticated/admin/programs'
import { Route as AuthenticatedAdminPodcastRouteImport } from './routes/_authenticated/admin/podcast'
import { Route as AuthenticatedAdminPartnersRouteImport } from './routes/_authenticated/admin/partners'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin/media'
import { Route as AuthenticatedAdminMarketsRouteImport } from './routes/_authenticated/admin/markets'
import { Route as AuthenticatedAdminInternshipsRouteImport } from './routes/_authenticated/admin/internships'
import { Route as AuthenticatedAdminGrantsRouteImport } from './routes/_authenticated/admin/grants'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin/events'
import { Route as AuthenticatedAdminEquipmentRouteImport } from './routes/_authenticated/admin/equipment'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysRoute = SurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipsRoute = InternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => rootRouteImport,
} as any)
const GrantsRoute = GrantsRouteImport.update({
  id: '/grants',
  path: '/grants',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsSlugRoute = PublicationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PublicationsRoute,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProgramsRoute,
} as any)
const MarketsIdRoute = MarketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MarketsRoute,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSurveysRoute =
  AuthenticatedAdminSurveysRouteImport.update({
    id: '/surveys',
    path: '/surveys',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSearchRoute =
  AuthenticatedAdminSearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPublicationsRoute =
  AuthenticatedAdminPublicationsRouteImport.update({
    id: '/publications',
    path: '/publications',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProgramsRoute =
  AuthenticatedAdminProgramsRouteImport.update({
    id: '/programs',
    path: '/programs',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPodcastRoute =
  AuthenticatedAdminPodcastRouteImport.update({
    id: '/podcast',
    path: '/podcast',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPartnersRoute =
  AuthenticatedAdminPartnersRouteImport.update({
    id: '/partners',
    path: '/partners',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminMarketsRoute =
  AuthenticatedAdminMarketsRouteImport.update({
    id: '/markets',
    path: '/markets',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminInternshipsRoute =
  AuthenticatedAdminInternshipsRouteImport.update({
    id: '/internships',
    path: '/internships',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminGrantsRoute =
  AuthenticatedAdminGrantsRouteImport.update({
    id: '/grants',
    path: '/grants',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEquipmentRoute =
  AuthenticatedAdminEquipmentRouteImport.update({
    id: '/equipment',
    path: '/equipment',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/donate': typeof DonateRoute
  '/equipment': typeof EquipmentRoute
  '/grants': typeof GrantsRoute
  '/internships': typeof InternshipsRoute
  '/markets': typeof MarketsRouteWithChildren
  '/partners': typeof PartnersRoute
  '/podcast': typeof PodcastRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/publications': typeof PublicationsRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/surveys': typeof SurveysRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/me': typeof AuthenticatedMeRoute
  '/events/$id': typeof EventsIdRoute
  '/markets/$id': typeof MarketsIdRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/publications/$slug': typeof PublicationsSlugRoute
  '/events/': typeof EventsIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/equipment': typeof AuthenticatedAdminEquipmentRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/grants': typeof AuthenticatedAdminGrantsRoute
  '/admin/internships': typeof AuthenticatedAdminInternshipsRoute
  '/admin/markets': typeof AuthenticatedAdminMarketsRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/podcast': typeof AuthenticatedAdminPodcastRoute
  '/admin/programs': typeof AuthenticatedAdminProgramsRoute
  '/admin/publications': typeof AuthenticatedAdminPublicationsRoute
  '/admin/search': typeof AuthenticatedAdminSearchRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/surveys': typeof AuthenticatedAdminSurveysRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/donate': typeof DonateRoute
  '/equipment': typeof EquipmentRoute
  '/grants': typeof GrantsRoute
  '/internships': typeof InternshipsRoute
  '/markets': typeof MarketsRouteWithChildren
  '/partners': typeof PartnersRoute
  '/podcast': typeof PodcastRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/publications': typeof PublicationsRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/surveys': typeof SurveysRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/me': typeof AuthenticatedMeRoute
  '/events/$id': typeof EventsIdRoute
  '/markets/$id': typeof MarketsIdRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/publications/$slug': typeof PublicationsSlugRoute
  '/events': typeof EventsIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/equipment': typeof AuthenticatedAdminEquipmentRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/grants': typeof AuthenticatedAdminGrantsRoute
  '/admin/internships': typeof AuthenticatedAdminInternshipsRoute
  '/admin/markets': typeof AuthenticatedAdminMarketsRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/podcast': typeof AuthenticatedAdminPodcastRoute
  '/admin/programs': typeof AuthenticatedAdminProgramsRoute
  '/admin/publications': typeof AuthenticatedAdminPublicationsRoute
  '/admin/search': typeof AuthenticatedAdminSearchRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/surveys': typeof AuthenticatedAdminSurveysRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/donate': typeof DonateRoute
  '/equipment': typeof EquipmentRoute
  '/grants': typeof GrantsRoute
  '/internships': typeof InternshipsRoute
  '/markets': typeof MarketsRouteWithChildren
  '/partners': typeof PartnersRoute
  '/podcast': typeof PodcastRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/publications': typeof PublicationsRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/surveys': typeof SurveysRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/events/$id': typeof EventsIdRoute
  '/markets/$id': typeof MarketsIdRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/publications/$slug': typeof PublicationsSlugRoute
  '/events/': typeof EventsIndexRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/equipment': typeof AuthenticatedAdminEquipmentRoute
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRoute
  '/_authenticated/admin/grants': typeof AuthenticatedAdminGrantsRoute
  '/_authenticated/admin/internships': typeof AuthenticatedAdminInternshipsRoute
  '/_authenticated/admin/markets': typeof AuthenticatedAdminMarketsRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/_authenticated/admin/podcast': typeof AuthenticatedAdminPodcastRoute
  '/_authenticated/admin/programs': typeof AuthenticatedAdminProgramsRoute
  '/_authenticated/admin/publications': typeof AuthenticatedAdminPublicationsRoute
  '/_authenticated/admin/search': typeof AuthenticatedAdminSearchRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/surveys': typeof AuthenticatedAdminSurveysRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/donate'
    | '/equipment'
    | '/grants'
    | '/internships'
    | '/markets'
    | '/partners'
    | '/podcast'
    | '/programs'
    | '/publications'
    | '/resources'
    | '/surveys'
    | '/unauthorized'
    | '/admin'
    | '/me'
    | '/events/$id'
    | '/markets/$id'
    | '/programs/$slug'
    | '/publications/$slug'
    | '/events/'
    | '/admin/analytics'
    | '/admin/equipment'
    | '/admin/events'
    | '/admin/grants'
    | '/admin/internships'
    | '/admin/markets'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/partners'
    | '/admin/podcast'
    | '/admin/programs'
    | '/admin/publications'
    | '/admin/search'
    | '/admin/settings'
    | '/admin/surveys'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/donate'
    | '/equipment'
    | '/grants'
    | '/internships'
    | '/markets'
    | '/partners'
    | '/podcast'
    | '/programs'
    | '/publications'
    | '/resources'
    | '/surveys'
    | '/unauthorized'
    | '/me'
    | '/events/$id'
    | '/markets/$id'
    | '/programs/$slug'
    | '/publications/$slug'
    | '/events'
    | '/admin/analytics'
    | '/admin/equipment'
    | '/admin/events'
    | '/admin/grants'
    | '/admin/internships'
    | '/admin/markets'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/partners'
    | '/admin/podcast'
    | '/admin/programs'
    | '/admin/publications'
    | '/admin/search'
    | '/admin/settings'
    | '/admin/surveys'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/donate'
    | '/equipment'
    | '/grants'
    | '/internships'
    | '/markets'
    | '/partners'
    | '/podcast'
    | '/programs'
    | '/publications'
    | '/resources'
    | '/surveys'
    | '/unauthorized'
    | '/_authenticated/admin'
    | '/_authenticated/me'
    | '/events/$id'
    | '/markets/$id'
    | '/programs/$slug'
    | '/publications/$slug'
    | '/events/'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/equipment'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/grants'
    | '/_authenticated/admin/internships'
    | '/_authenticated/admin/markets'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/partners'
    | '/_authenticated/admin/podcast'
    | '/_authenticated/admin/programs'
    | '/_authenticated/admin/publications'
    | '/_authenticated/admin/search'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/surveys'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DonateRoute: typeof DonateRoute
  EquipmentRoute: typeof EquipmentRoute
  GrantsRoute: typeof GrantsRoute
  InternshipsRoute: typeof InternshipsRoute
  MarketsRoute: typeof MarketsRouteWithChildren
  PartnersRoute: typeof PartnersRoute
  PodcastRoute: typeof PodcastRoute
  ProgramsRoute: typeof ProgramsRouteWithChildren
  PublicationsRoute: typeof PublicationsRouteWithChildren
  ResourcesRoute: typeof ResourcesRoute
  SurveysRoute: typeof SurveysRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  EventsIdRoute: typeof EventsIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys': {
      id: '/surveys'
      path: '/surveys'
      fullPath: '/surveys'
      preLoaderRoute: typeof SurveysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internships': {
      id: '/internships'
      path: '/internships'
      fullPath: '/internships'
      preLoaderRoute: typeof InternshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grants': {
      id: '/grants'
      path: '/grants'
      fullPath: '/grants'
      preLoaderRoute: typeof GrantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications/$slug': {
      id: '/publications/$slug'
      path: '/$slug'
      fullPath: '/publications/$slug'
      preLoaderRoute: typeof PublicationsSlugRouteImport
      parentRoute: typeof PublicationsRoute
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/markets/$id': {
      id: '/markets/$id'
      path: '/$id'
      fullPath: '/markets/$id'
      preLoaderRoute: typeof MarketsIdRouteImport
      parentRoute: typeof MarketsRoute
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/surveys': {
      id: '/_authenticated/admin/surveys'
      path: '/surveys'
      fullPath: '/admin/surveys'
      preLoaderRoute: typeof AuthenticatedAdminSurveysRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/search': {
      id: '/_authenticated/admin/search'
      path: '/search'
      fullPath: '/admin/search'
      preLoaderRoute: typeof AuthenticatedAdminSearchRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/publications': {
      id: '/_authenticated/admin/publications'
      path: '/publications'
      fullPath: '/admin/publications'
      preLoaderRoute: typeof AuthenticatedAdminPublicationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/programs': {
      id: '/_authenticated/admin/programs'
      path: '/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AuthenticatedAdminProgramsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/podcast': {
      id: '/_authenticated/admin/podcast'
      path: '/podcast'
      fullPath: '/admin/podcast'
      preLoaderRoute: typeof AuthenticatedAdminPodcastRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/partners': {
      id: '/_authenticated/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AuthenticatedAdminPartnersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/markets': {
      id: '/_authenticated/admin/markets'
      path: '/markets'
      fullPath: '/admin/markets'
      preLoaderRoute: typeof AuthenticatedAdminMarketsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/internships': {
      id: '/_authenticated/admin/internships'
      path: '/internships'
      fullPath: '/admin/internships'
      preLoaderRoute: typeof AuthenticatedAdminInternshipsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/grants': {
      id: '/_authenticated/admin/grants'
      path: '/grants'
      fullPath: '/admin/grants'
      preLoaderRoute: typeof AuthenticatedAdminGrantsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/equipment': {
      id: '/_authenticated/admin/equipment'
      path: '/equipment'
      fullPath: '/admin/equipment'
      preLoaderRoute: typeof AuthenticatedAdminEquipmentRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminEquipmentRoute: typeof AuthenticatedAdminEquipmentRoute
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRoute
  AuthenticatedAdminGrantsRoute: typeof AuthenticatedAdminGrantsRoute
  AuthenticatedAdminInternshipsRoute: typeof AuthenticatedAdminInternshipsRoute
  AuthenticatedAdminMarketsRoute: typeof AuthenticatedAdminMarketsRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminPartnersRoute: typeof AuthenticatedAdminPartnersRoute
  AuthenticatedAdminPodcastRoute: typeof AuthenticatedAdminPodcastRoute
  AuthenticatedAdminProgramsRoute: typeof AuthenticatedAdminProgramsRoute
  AuthenticatedAdminPublicationsRoute: typeof AuthenticatedAdminPublicationsRoute
  AuthenticatedAdminSearchRoute: typeof AuthenticatedAdminSearchRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSurveysRoute: typeof AuthenticatedAdminSurveysRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
    AuthenticatedAdminEquipmentRoute: AuthenticatedAdminEquipmentRoute,
    AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRoute,
    AuthenticatedAdminGrantsRoute: AuthenticatedAdminGrantsRoute,
    AuthenticatedAdminInternshipsRoute: AuthenticatedAdminInternshipsRoute,
    AuthenticatedAdminMarketsRoute: AuthenticatedAdminMarketsRoute,
    AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
    AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
    AuthenticatedAdminPartnersRoute: AuthenticatedAdminPartnersRoute,
    AuthenticatedAdminPodcastRoute: AuthenticatedAdminPodcastRoute,
    AuthenticatedAdminProgramsRoute: AuthenticatedAdminProgramsRoute,
    AuthenticatedAdminPublicationsRoute: AuthenticatedAdminPublicationsRoute,
    AuthenticatedAdminSearchRoute: AuthenticatedAdminSearchRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminSurveysRoute: AuthenticatedAdminSurveysRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface MarketsRouteChildren {
  MarketsIdRoute: typeof MarketsIdRoute
}

const MarketsRouteChildren: MarketsRouteChildren = {
  MarketsIdRoute: MarketsIdRoute,
}

const MarketsRouteWithChildren =
  MarketsRoute._addFileChildren(MarketsRouteChildren)

interface ProgramsRouteChildren {
  ProgramsSlugRoute: typeof ProgramsSlugRoute
}

const ProgramsRouteChildren: ProgramsRouteChildren = {
  ProgramsSlugRoute: ProgramsSlugRoute,
}

const ProgramsRouteWithChildren = ProgramsRoute._addFileChildren(
  ProgramsRouteChildren,
)

interface PublicationsRouteChildren {
  PublicationsSlugRoute: typeof PublicationsSlugRoute
}

const PublicationsRouteChildren: PublicationsRouteChildren = {
  PublicationsSlugRoute: PublicationsSlugRoute,
}

const PublicationsRouteWithChildren = PublicationsRoute._addFileChildren(
  PublicationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DonateRoute: DonateRoute,
  EquipmentRoute: EquipmentRoute,
  GrantsRoute: GrantsRoute,
  InternshipsRoute: InternshipsRoute,
  MarketsRoute: MarketsRouteWithChildren,
  PartnersRoute: PartnersRoute,
  PodcastRoute: PodcastRoute,
  ProgramsRoute: ProgramsRouteWithChildren,
  PublicationsRoute: PublicationsRouteWithChildren,
  ResourcesRoute: ResourcesRoute,
  SurveysRoute: SurveysRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  EventsIdRoute: EventsIdRoute,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
